Repository 100-hours-a-week/10-wingterview-fe, pull requests merged in 2025-05, with the labels that each got.

#15 [style] 최초 로그인한 유저의 프로필 설정 페이지 UI
  package-lock.json
  package.json
  src/api/authAPI.ts
  src/assets/default-profile.png
  src/components/auth/KakaoLoginButton/KakaoLoginButton.tsx
  src/components/auth/index.ts
  src/components/common/SeatMap/SeatMap.tsx
  src/components/common/SeatMap/styles.module.scss
  src/components/common/_ui/ClickableTag/ClickableTag.tsx
  src/components/common/_ui/ClickableTag/styles.module.scss
  src/components/common/_ui/Dropdown/Dropdown.tsx
  src/components/common/_ui/Dropdown/styles.module.scss
  src/components/common/_ui/StaticTag/StaticTag.tsx
  src/components/common/_ui/StaticTag/styles.module.scss
  src/components/common/index.ts
  src/components/profile/ProfileCard/ProfileCard.tsx
  src/components/profile/ProfileCard/styles.module.scss
  src/components/profile/ProfileSlider/ProfileSlider.tsx
  src/components/profile/ProfileSlider/styles.module.scss
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/profile/SliderButtons/styles.module.scss
  src/components/profile/_steps/BasicInfoStep/BasicInfoStep.tsx
  src/components/profile/_steps/BasicInfoStep/styles.module.scss
  src/components/profile/_steps/FinalConfirmStep/FinalConfirmStep.tsx
  src/components/profile/_steps/FinalConfirmStep/styles.module.scss
  src/components/profile/_steps/JobInterestStep/JobInterestStep.tsx
  src/components/profile/_steps/JobInterestStep/styles.module.scss
  src/components/profile/_steps/ProfileImageStep/ProfileImageStep.tsx
  src/components/profile/_steps/ProfileImageStep/styles.module.scss
  src/components/profile/_steps/SeatLocationStep/SeatLocationStep.tsx
  src/components/profile/_steps/SeatLocationStep/styles.module.scss
  src/components/profile/_steps/TechStackStep/TechStackStep.tsx
  src/components/profile/_steps/TechStackStep/styles.module.scss
  src/components/profile/_steps/index.ts
  src/components/profile/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/auth/LoginPage/LoginPage.tsx
  src/pages/auth/LoginPage/styles.module.scss
  src/pages/auth/LoginRedirectPage/LoginRedirectPage.tsx
  src/pages/auth/LoginRedirectPage/styles.module.scss
  src/pages/auth/ProfileSetupPage/ProfileSetupPage.tsx
  src/pages/auth/ProfileSetupPage/styles.module.scss
  src/pages/index.ts
  src/routes/index.tsx
  src/stores/authStore.ts
  src/types/index.d.ts
  src/types/swiper.d.ts
Labels: style 💄, FE, new feature ✨

#16 [feat] 프로필 데이터 상태 관리 store 추가
  src/api/ profileAPI.ts
  src/components/common/SeatMap/SeatMap.tsx
  src/components/profile/ProfileSlider/ProfileSlider.tsx
  src/components/profile/ProfileSlider/styles.module.scss
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/profile/SliderButtons/styles.module.scss
  src/components/profile/_steps/BasicInfoStep/BasicInfoStep.tsx
  src/components/profile/_steps/FinalConfirmStep/FinalConfirmStep.tsx
  src/components/profile/_steps/FinalConfirmStep/styles.module.scss
  src/components/profile/_steps/JobInterestStep/JobInterestStep.tsx
  src/components/profile/_steps/ProfileImageStep/ProfileImageStep.tsx
  src/components/profile/_steps/SeatLocationStep/SeatLocationStep.tsx
  src/components/profile/_steps/TechStackStep/TechStackStep.tsx
  src/components/profile/valid.txt
  src/stores/profileStore.ts
  src/types/index.d.ts
  src/utils/validators.ts
Labels: new feature ✨

#18 [fix] API 통신 연결 중 발생한 에러 수정 (카카오 로그인 & 회원 프로필 설정)
  src/api/apiClient.ts
  src/api/authAPI.ts
  src/api/profileAPI.ts
  src/components/common/_ui/ClickableTag/ClickableTag.tsx
  src/components/common/_ui/ClickableTag/styles.module.scss
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/profile/_steps/JobInterestStep/JobInterestStep.tsx
  src/components/profile/_steps/TechStackStep/TechStackStep.tsx
  src/pages/auth/LoginRedirectPage/LoginRedirectPage.tsx
  src/pages/auth/ProfileSetupPage/ProfileSetupPage.tsx
  src/stores/authStore.ts
  src/types/index.d.ts
Labels: fix bug 🐛, FE

#19 [feat] 프로필 유효성 검사 로직 작성 및 에러 메세지 UI 컴포넌트 추가
  src/components/common/SeatMap/SeatMap.tsx
  src/components/common/_ui/Dropdown/Dropdown.tsx
  src/components/common/_ui/ErrorMessage/ErrorMessage.tsx
  src/components/common/_ui/ErrorMessage/styles.module.scss
  src/components/common/index.ts
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/profile/_steps/BasicInfoStep/BasicInfoStep.tsx
  src/components/profile/_steps/BasicInfoStep/styles.module.scss
  src/components/profile/_steps/FinalConfirmStep/FinalConfirmStep.tsx
  src/components/profile/_steps/JobInterestStep/JobInterestStep.tsx
  src/components/profile/_steps/JobInterestStep/styles.module.scss
  src/components/profile/_steps/SeatLocationStep/SeatLocationStep.tsx
  src/components/profile/_steps/SeatLocationStep/styles.module.scss
  src/components/profile/_steps/TechStackStep/TechStackStep.tsx
  src/components/profile/_steps/TechStackStep/styles.module.scss
  src/stores/profileStore.ts
  src/types/index.d.ts
  src/utils/validators.ts
Labels: FE, new feature ✨

#21 [style] 네비게이션 메뉴바 및 준비중 페이지 UI 추가
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/styles.module.scss
  src/components/common/_layout/Page/Page.tsx
  src/components/common/_layout/Page/styles.module.scss
  src/components/common/_layout/ProtectedLayout/ProtectedLayout.tsx
  src/components/common/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/auth/LoginPage/LoginPage.tsx
  src/pages/auth/LoginPage/styles.module.scss
  src/pages/auth/LoginRedirectPage/LoginRedirectPage.tsx
  src/pages/auth/LoginRedirectPage/styles.module.scss
  src/pages/auth/ProfileSetupPage/ProfileSetupPage.tsx
  src/pages/auth/ProfileSetupPage/styles.module.scss
  src/pages/common/ComingSoonPage/ComingSoonPage.tsx
  src/pages/common/ComingSoonPage/styles.module.scss
  src/pages/home/HomePage/HomePage.tsx
  src/pages/home/HomePage/styles.module.scss
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/_variables.scss
Labels: style 💄, FE

#23 [bugfix] Seat 데이터 타입 수정 및 유효성 검사 처리
  src/components/common/SeatMap/SeatMap.tsx
  src/components/profile/_steps/FinalConfirmStep/FinalConfirmStep.tsx
  src/components/profile/_steps/SeatLocationStep/SeatLocationStep.tsx
  src/stores/profileStore.ts
  src/types/index.d.ts
  src/utils/validators.ts
Labels: fix bug 🐛, FE

#22 [feat] 1:1 매칭 대기 페이지 UI & 내 정보 조회, 매칭 큐 진입, 신청자 수 조회 API
  src/api/matchAPI.ts
  src/api/profileAPI.ts
  src/api/userAPI.ts
  src/assets/logo-dark.png
  src/assets/logo-light.png
  src/components/common/ProfileCard/ProfileCard.tsx
  src/components/common/ProfileCard/styles.module.scss
  src/components/common/_ui/Button/Button.tsx
  src/components/common/_ui/Button/styles.module.scss
  src/components/common/_ui/LoadingIndicator/LoadingIndicator.tsx
  src/components/common/_ui/LoadingIndicator/styles.module.scss
  src/components/common/_ui/Logo/Logo.tsx
  src/components/common/_ui/Logo/styles.module.scss
  src/components/common/index.ts
  src/components/profile/ProfileFormLayout/ProfileFormLayout.tsx
  src/components/profile/ProfileFormLayout/styles.module.scss
  src/components/profile/_steps/BasicInfoStep/BasicInfoStep.tsx
  src/components/profile/_steps/FinalConfirmStep/FinalConfirmStep.tsx
  src/components/profile/_steps/JobInterestStep/JobInterestStep.tsx
  src/components/profile/_steps/ProfileImageStep/ProfileImageStep.tsx
  src/components/profile/_steps/SeatLocationStep/SeatLocationStep.tsx
  src/components/profile/_steps/TechStackStep/TechStackStep.tsx
  src/components/profile/index.ts
  src/hooks/match.ts
  src/hooks/useMyProfile.ts
  src/pages/auth/LoginRedirectPage/LoginRedirectPage.tsx
  src/pages/auth/LoginRedirectPage/styles.module.scss
  src/pages/common/ComingSoonPage/ComingSoonPage.tsx
  src/pages/common/ComingSoonPage/styles.module.scss
  src/pages/home/HomePage/HomePage.tsx
  src/pages/home/HomePage/styles.module.scss
  src/pages/index.ts
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/pages/match/MatchResultPage/styles.module.scss
  src/routes/index.tsx
  src/stores/profileStore.ts
  src/types/index.d.ts
  src/types/user.d.ts
Labels: FE, new feature ✨

#38 [feat] 1:1 모의면접 매칭 결과 페이지 UI 및 매칭 결과 프로필 API 추가
  src/api/matchAPI.ts
  src/components/match/MatchInfoCard/MatchInfoCard.tsx
  src/components/match/MatchInfoCard/styles.module.scss
  src/components/match/index.ts
  src/pages/home/HomePage/HomePage.tsx
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/pages/match/MatchResultPage/styles.module.scss
  src/stores/matchStore.ts
  src/types/match.d.ts
Labels: FE, new feature ✨

#39 [style] 면접 시작 전/진행 중/피드백 전송 페이지 UI
  src/components/common/Navbar/Navbar.tsx
  src/components/common/_layout/InterviewLayout/InterviewLayout.tsx
  src/components/common/_layout/InterviewLayout/styles.module.scss
  src/components/common/_ui/Button/styles.module.scss
  src/components/common/index.ts
  src/pages/index.ts
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAnswerPage/styles.module.scss
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewAwaitingPage/styles.module.scss
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/interview/InterviewFeedbackPage/styles.module.scss
  src/pages/interview/InterviewQuestionPage/InterviewQuestionPage.tsx
  src/pages/interview/InterviewQuestionPage/styles.module.scss
  src/routes/index.tsx
Labels: FE, new feature ✨

#42 [feat] 면접 상태 조회 / 면접 질문 생성 / 선택한 질문 전송 API 연동
  src/api/interviewAPI.ts
  src/components/common/ProfileCard/ProfileCard.tsx
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/hooks/interview.ts
  src/hooks/match.ts
  src/pages/home/HomePage/HomePage.tsx
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewAwaitingPage/styles.module.scss
  src/pages/interview/InterviewQuestionPage/InterviewQuestionPage.tsx
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/stores/interviewStore.ts
  src/stores/matchStore.ts
  src/types/interview.d.ts
Labels: FE, new feature ✨

#43 [feat] 면접 임시 종료 버튼으로 상태 변경 테스트 및 로딩 중 모달 UI
  src/api/interviewAPI.ts
  src/assets/sad.png
  src/components/common/Navbar/Navbar.tsx
  src/components/common/_layout/Page/styles.module.scss
  src/components/common/_ui/LoadingIndicator/styles.module.scss
  src/components/common/_ui/Modal/Modal.tsx
  src/components/common/_ui/Modal/styles.module.scss
  src/components/common/index.ts
  src/hooks/interview.ts
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAnswerPage/styles.module.scss
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/interview/InterviewFeedbackPage/styles.module.scss
  src/pages/interview/InterviewQuestionPage/InterviewQuestionPage.tsx
Labels: FE, new feature ✨

#45 [feat] MSW(Mock Service Worker) 설정 및 API 모의응답 테스트
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/apiClient.ts
  src/api/authAPI.ts
  src/api/endpoints/index.ts
  src/api/interviewAPI.ts
  src/api/matchAPI.ts
  src/api/profileAPI.ts
  src/api/seatAPI.ts
  src/api/userAPI.ts
  src/components/common/ProfileCard/styles.module.scss
  src/components/common/_layout/InterviewLayout/styles.module.scss
  src/components/common/_layout/Page/styles.module.scss
  src/components/match/MatchInfoCard/styles.module.scss
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/seat/SeatMap/SeatMap.tsx
  src/hooks/interview.ts
  src/hooks/match.ts
  src/hooks/profile.ts
  src/hooks/seat.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/common/ComingSoonPage/styles.module.scss
  src/pages/home/HomePage/HomePage.tsx
  src/pages/home/HomePage/styles.module.scss
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewAwaitingPage/styles.module.scss
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/interview/InterviewFeedbackPage/styles.module.scss
  src/pages/interview/InterviewQuestionPage/InterviewQuestionPage.tsx
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/pages/match/MatchResultPage/styles.module.scss
  src/stores/profileStore.ts
  vite.config.ts
Labels: FE, new feature ✨

#46 [bugfix] 프로필 이미지 url 및 인터뷰 질문 refresh 로직 수정
  package-lock.json
  package.json
  src/components/common/Navbar/styles.module.scss
  src/components/common/ProfileCard/ProfileCard.tsx
  src/components/common/ProfileCard/styles.module.scss
  src/components/common/_layout/InterviewLayout/styles.module.scss
  src/components/common/_layout/Page/styles.module.scss
  src/components/common/_layout/RootLayout/styles.module.scss
  src/components/common/_ui/Button/styles.module.scss
  src/components/common/_ui/ClickableTag/styles.module.scss
  src/components/common/_ui/Dropdown/styles.module.scss
  src/components/common/_ui/Logo/Logo.tsx
  src/components/common/_ui/Logo/styles.module.scss
  src/components/common/_ui/StaticTag/styles.module.scss
  src/components/match/MatchInfoCard/MatchInfoCard.tsx
  src/components/match/MatchInfoCard/styles.module.scss
  src/components/profile/ProfileFormLayout/styles.module.scss
  src/components/profile/ProfileSlider/ProfileSlider.tsx
  src/components/profile/ProfileSlider/styles.module.scss
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/profile/SliderButtons/styles.module.scss
  src/components/profile/_steps/BasicInfoStep/styles.module.scss
  src/components/profile/_steps/FinalConfirmStep/FinalConfirmStep.tsx
  src/components/profile/_steps/FinalConfirmStep/styles.module.scss
  src/components/profile/_steps/JobInterestStep/styles.module.scss
  src/components/profile/_steps/ProfileImageStep/ProfileImageStep.tsx
  src/components/profile/_steps/ProfileImageStep/styles.module.scss
  src/components/profile/_steps/SeatLocationStep/styles.module.scss
  src/components/profile/_steps/TechStackStep/styles.module.scss
  src/components/seat/SeatInfoCard/styles.module.scss
  src/components/seat/SeatMap/styles.module.scss
  src/components/seat/SeatMapSection/styles.module.scss
  src/mocks/handlers.ts
  src/pages/auth/ProfileSetupPage/ProfileSetupPage.tsx
  src/pages/auth/ProfileSetupPage/styles.module.scss
  src/pages/common/ComingSoonPage/styles.module.scss
  src/pages/home/HomePage/HomePage.tsx
  src/pages/home/HomePage/styles.module.scss
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAnswerPage/styles.module.scss
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewAwaitingPage/styles.module.scss
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/interview/InterviewFeedbackPage/styles.module.scss
  src/pages/interview/InterviewQuestionPage/InterviewQuestionPage.tsx
  src/pages/interview/InterviewQuestionPage/styles.module.scss
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/pages/match/MatchResultPage/styles.module.scss
  src/stores/interviewStore.ts
  src/stores/profileStore.ts
  src/types/user.d.ts
  vite.config.ts
Labels: fix bug 🐛, FE

#48 [feat] 면접관 자리 보기 기능 추가 및 자리 배치도 스타일 수정
  src/api/seatAPI.ts
  src/components/profile/_steps/SeatLocationStep/SeatLocationStep.tsx
  src/components/seat/SeatMap/SeatMap.tsx
  src/components/seat/SeatMap/styles.module.scss
  src/components/seat/SeatMapSection/SeatMapSection.tsx
  src/components/seat/SeatMapSection/styles.module.scss
  src/hooks/seat.ts
  src/mocks/handlers.ts
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/types/seat.d.ts
  src/utils/parseSeatCode.ts
Labels: FE, new feature ✨

#49 [feat] 면접 상태에 따른 타이머 가동/정지 기능 구현
  src/components/common/_layout/InterviewLayout/InterviewLayout.tsx
  src/components/common/_layout/InterviewLayout/styles.module.scss
  src/components/interview/Timer/Timer.tsx
  src/components/interview/Timer/styles.module.scss
  src/components/interview/index.ts
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/stores/interviewStore.ts
  src/stores/timerStore.ts
Labels: FE, new feature ✨

#51 [bugfix] 프로필 제출 시 이미지 url 타입 수정
  src/components/common/_layout/InterviewLayout/InterviewLayout.tsx
  src/components/common/_layout/InterviewLayout/styles.module.scss
  src/components/common/_ui/Modal/Modal.tsx
  src/components/common/_ui/Modal/styles.module.scss
  src/components/interview/Timer/styles.module.scss
  src/components/profile/_steps/ProfileImageStep/ProfileImageStep.tsx
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/stores/profileStore.ts
  src/types/user.d.ts
Labels: fix bug 🐛, FE

#53 [feat] 면접관/면접자 역할 자동 스위칭 기능 및 color palette 추가
  src/api/interviewAPI.ts
  src/assets/wait.png
  src/assets/wing-l.png
  src/assets/wing-r.png
  src/components/common/ProfileCard/styles.module.scss
  src/components/common/_layout/InterviewLayout/InterviewLayout.tsx
  src/components/common/_layout/InterviewLayout/styles.module.scss
  src/components/common/_layout/RootLayout/styles.module.scss
  src/components/common/_ui/Button/styles.module.scss
  src/components/common/_ui/ClickableTag/styles.module.scss
  src/components/common/_ui/ErrorMessage/styles.module.scss
  src/components/common/_ui/Modal/Modal.tsx
  src/components/common/_ui/Modal/styles.module.scss
  src/components/interview/CurrentRound/CurrentRound.tsx
  src/components/interview/CurrentRound/styles.module.scss
  src/components/interview/StarRating/StarRating.tsx
  src/components/interview/StarRating/styles.module.scss
  src/components/interview/index.ts
  src/components/match/MatchInfoCard/styles.module.scss
  src/components/profile/ProfileFormLayout/styles.module.scss
  src/components/profile/ProfileSlider/styles.module.scss
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/profile/SliderButtons/styles.module.scss
  src/components/profile/_steps/BasicInfoStep/BasicInfoStep.tsx
  src/components/profile/_steps/FinalConfirmStep/styles.module.scss
  src/components/seat/SeatInfoCard/styles.module.scss
  src/components/seat/SeatMapSection/styles.module.scss
  src/hooks/interview.ts
  src/pages/auth/ProfileSetupPage/styles.module.scss
  src/pages/common/ComingSoonPage/styles.module.scss
  src/pages/home/HomePage/HomePage.tsx
  src/pages/home/HomePage/styles.module.scss
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAnswerPage/styles.module.scss
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewAwaitingPage/styles.module.scss
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/interview/InterviewFeedbackPage/styles.module.scss
  src/pages/interview/InterviewQuestionPage/InterviewQuestionPage.tsx
  src/pages/interview/InterviewQuestionPage/styles.module.scss
  src/pages/match/MatchResultPage/styles.module.scss
  src/stores/interviewStore.ts
  src/stores/matchStore.ts
  src/styles/_reset.scss
  src/styles/_variables.scss
  src/types/interview.d.ts
Labels: FE, new feature ✨

#100 Create qa-template.md
  .github/ISSUE_TEMPLATE/qa-template.md
Labels: 문서화

#103 [feat] 인터뷰 관련 데이터 캐싱 후 새로고침해도 화면이 유지되도록 처리
  src/api/matchAPI.ts
  src/components/common/Navbar/Navbar.tsx
  src/components/common/_layout/InterviewLayout/InterviewLayout.tsx
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAnswerPage/styles.module.scss
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/interview/InterviewQuestionPage/InterviewQuestionPage.tsx
  src/stores/interviewStore.ts
  src/types/interview.d.ts
  src/utils/getInterviewRouteByPhase.ts
  src/utils/index.ts
Labels: refactor ♻, FE, new feature ✨

#106 [bugfix] 매칭 결과 요청 및 인터뷰 분기 처리 관련 예외처리
  src/api/matchAPI.ts
  src/api/profileAPI.ts
  src/components/common/ProfileCard/ProfileCard.tsx
  src/components/common/_layout/InterviewLayout/InterviewLayout.tsx
  src/components/match/MatchInfoCard/MatchInfoCard.tsx
  src/hooks/interview.ts
  src/hooks/match.ts
  src/hooks/profile.ts
  src/pages/home/HomePage/HomePage.tsx
  src/pages/interview/InterviewAnswerPage/InterviewAnswerPage.tsx
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/interview/InterviewQuestionPage/InterviewQuestionPage.tsx
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/stores/timerStore.ts
  src/types/match.d.ts
  src/types/user.d.ts
Labels: fix bug 🐛, FE

#115 [refactor] 프로필 설정 페이지 관련 이슈 반영
  src/components/common/ProfileCard/ProfileCard.tsx
  src/components/common/ProfileCard/styles.module.scss
  src/components/common/_layout/ProtectedLayout/ProtectedLayout.tsx
  src/components/common/_ui/ProfileImage/ProfileImage.tsx
  src/components/common/_ui/ProfileImage/styles.module.scss
  src/components/common/index.ts
  src/components/match/MatchInfoCard/MatchInfoCard.tsx
  src/components/profile/ProfileFormLayout/styles.module.scss
  src/components/profile/ProfileSlider/ProfileSlider.tsx
  src/components/profile/ProfileSlider/styles.module.scss
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/profile/SliderButtons/styles.module.scss
  src/components/profile/_steps/BasicInfoStep/BasicInfoStep.tsx
  src/components/profile/_steps/FinalConfirmStep/FinalConfirmStep.tsx
  src/components/profile/_steps/FinalConfirmStep/styles.module.scss
  src/components/profile/_steps/JobInterestStep/JobInterestStep.tsx
  src/components/profile/_steps/ProfileImageStep/ProfileImageStep.tsx
  src/components/profile/_steps/ProfileImageStep/styles.module.scss
  src/components/profile/_steps/SeatLocationStep/SeatLocationStep.tsx
  src/components/profile/_steps/TechStackStep/TechStackStep.tsx
  src/pages/auth/LoginRedirectPage/LoginRedirectPage.tsx
  src/pages/auth/ProfileSetupPage/ProfileSetupPage.tsx
  src/pages/auth/ProfileSetupPage/styles.module.scss
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewAwaitingPage/styles.module.scss
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/routes/index.tsx
  src/stores/authStore.ts
  src/stores/index.ts
  src/stores/profileStore.ts
  src/types/user.d.ts
Labels: refactor ♻, FE

#117 [release] v.1.1.2
  src/api/endpoints/index.ts
  src/api/profileAPI.ts
  src/components/auth/KakaoLoginButton/KakaoLoginButton.tsx
  src/components/common/ProfileCard/ProfileCard.tsx
  src/components/common/ProfileCard/styles.module.scss
  src/components/common/_layout/ProtectedLayout/ProtectedLayout.tsx
  src/components/common/_ui/ProfileImage/ProfileImage.tsx
  src/components/common/_ui/ProfileImage/styles.module.scss
  src/components/common/index.ts
  src/components/match/MatchInfoCard/MatchInfoCard.tsx
  src/components/profile/ProfileFormLayout/styles.module.scss
  src/components/profile/ProfileSlider/ProfileSlider.tsx
  src/components/profile/ProfileSlider/styles.module.scss
  src/components/profile/SliderButtons/SliderButtons.tsx
  src/components/profile/SliderButtons/styles.module.scss
  src/components/profile/_steps/BasicInfoStep/BasicInfoStep.tsx
  src/components/profile/_steps/FinalConfirmStep/FinalConfirmStep.tsx
  src/components/profile/_steps/FinalConfirmStep/styles.module.scss
  src/components/profile/_steps/JobInterestStep/JobInterestStep.tsx
  src/components/profile/_steps/ProfileImageStep/ProfileImageStep.tsx
  src/components/profile/_steps/ProfileImageStep/styles.module.scss
  src/components/profile/_steps/SeatLocationStep/SeatLocationStep.tsx
  src/components/profile/_steps/TechStackStep/TechStackStep.tsx
  src/hooks/presigned.ts
  src/hooks/profile.ts
  src/mocks/handlers.ts
  src/pages/auth/LoginPage/LoginPage.tsx
  src/pages/auth/LoginRedirectPage/LoginRedirectPage.tsx
  src/pages/auth/ProfileSetupPage/ProfileSetupPage.tsx
  src/pages/auth/ProfileSetupPage/styles.module.scss
  src/pages/interview/InterviewAwaitingPage/InterviewAwaitingPage.tsx
  src/pages/interview/InterviewAwaitingPage/styles.module.scss
  src/pages/interview/InterviewFeedbackPage/InterviewFeedbackPage.tsx
  src/pages/match/MatchAwaitingPage/MatchAwaitingPage.tsx
  src/pages/match/MatchResultPage/MatchResultPage.tsx
  src/routes/index.tsx
  src/stores/authStore.ts
  src/stores/index.ts
  src/stores/profileStore.ts
  src/types/user.d.ts
Labels: release 🎉
